"""Appelman et al. 2024 (Nat Commun 15:17) Source Data: Long COVID vs healthy, PEM induction, metabolomics.

Registers the source `appelman_lc_pem_source` (download via `measure_it.download`, MANIFEST.json, DATA_AUDIT.md,
registry_entry.yaml) and exposes `load_*` readers used by `measure_it.labs.appelman_metabolomics`. Every count in the
audit is computed from the file. Group-by-outcome statistics are NOT computed here (they belong to the locked
analysis plan docs/ANALYSIS_PLAN_LABS_VS_DIAGNOSIS.md).

    uv run python -m measure_it.ingestion.appelman_lc_pem
"""
from __future__ import annotations

import hashlib
import json

import pandas as pd

from ..config import raw_dir, utc_now_iso
from ..download import download_file, load_manifest
from ..registry import write_registry_entry

SOURCE_ID = "appelman_lc_pem_source"
URL = ("https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-023-44432-3/MediaObjects/"
       "41467_2023_44432_MOESM4_ESM.xlsx")
FILENAME = "41467_2023_44432_MOESM4_ESM.xlsx"
DOI = "10.1038/s41467-023-44432-3"
SHEET_BLOOD = "Supplementary Data Figure 6B"
SHEET_MUSCLE = "Supplementary Data Figure 6A"
SHEET_DOMAIN_BLOOD = "Supp. Fig 6B - Domain blood"
SHEET_DOMAIN_MUSCLE = "Supp. Fig 6A - Domain Muscle"
SHEET_DEMOG = "Table 1"
SHEET_VO2 = "Figure1"
GROUPS = {"Long COVID": 1, "Healthy": 0}
META_COLS = ("ID", "Group", "Time")


def fetch() -> "Path":  # noqa: F821
    return download_file(URL, SOURCE_ID, FILENAME, min_bytes=100_000)


def path():
    return raw_dir(SOURCE_ID) / FILENAME


def load_metabolomics(tissue: str) -> tuple[pd.DataFrame, list[str]]:
    """Long table (ID, Group, Time, <metabolites>) exactly as released; tissue in {'blood', 'muscle'}."""
    sheet = SHEET_BLOOD if tissue == "blood" else SHEET_MUSCLE
    d = pd.read_excel(path(), sheet_name=sheet)
    mets = [c for c in d.columns if c not in META_COLS]
    d["ID"] = d["ID"].astype(int)
    return d, mets


def load_domains(tissue: str) -> pd.DataFrame:
    sheet = SHEET_DOMAIN_BLOOD if tissue == "blood" else SHEET_DOMAIN_MUSCLE
    return pd.read_excel(path(), sheet_name=sheet).dropna(subset=["Metabolite"])


def load_demographics() -> pd.DataFrame:
    t = pd.read_excel(path(), sheet_name=SHEET_DEMOG)
    t = t.rename(columns={c: "age_not_released" for c in t.columns if str(c).startswith("age")})
    t["ID"] = t["ID"].astype(int)
    t["female"] = (t["sex"] == "Female").astype(float)
    t["long_covid"] = t["Group"].map(GROUPS)
    return t


def load_vo2() -> pd.DataFrame:
    f = pd.read_excel(path(), sheet_name=SHEET_VO2)
    f = f.rename(columns={c: "age_not_released" for c in f.columns if str(c).startswith("age")})
    f["ID"] = f["ID"].astype(int)
    return f[["ID", "VO2max", "peakpoweroutput", "GET"]]


def _counts() -> dict:
    demo = load_demographics()
    out = {"table1_people": int(len(demo)),
           "table1_by_group_sex": {g: {s: int(n) for s, n in x["sex"].value_counts().items()}
                                   for g, x in demo.groupby("Group")},
           "bmi_nonmissing": int(demo["bmi"].notna().sum()),
           "age_released": bool(demo["age_not_released"].notna().any())}
    for tissue in ("blood", "muscle"):
        d, mets = load_metabolomics(tissue)
        out[f"{tissue}_metabolites"] = len(mets)
        out[f"{tissue}_rows"] = int(len(d))
        out[f"{tissue}_group_time"] = {f"{g}|{t}": int(n) for (g, t), n in d.groupby(["Group", "Time"]).size().items()}
        out[f"{tissue}_missing_cells"] = int(d[mets].isna().sum().sum())
        out[f"{tissue}_nonpositive_cells"] = int((d[mets] <= 0).sum().sum())
        out[f"{tissue}_baseline_ids"] = int(d.loc[d["Time"] == "Baseline", "ID"].nunique())
    vo2 = load_vo2()
    b, _ = load_metabolomics("blood")
    m, _ = load_metabolomics("muscle")
    bb = set(b.loc[b["Time"] == "Baseline", "ID"])
    mb = set(m.loc[m["Time"] == "Baseline", "ID"])
    v = set(vo2.loc[vo2["VO2max"].notna(), "ID"])
    grp = demo.set_index("ID")["Group"]
    out["overlap"] = {name: {g: int(sum(grp.get(i) == g for i in ids)) for g in GROUPS}
                      for name, ids in (("baseline_blood", bb), ("baseline_muscle", mb), ("vo2max", v),
                                        ("blood_and_muscle", bb & mb), ("vo2max_and_blood", v & bb),
                                        ("vo2max_and_muscle", v & mb))}
    out["ids_not_in_table1"] = sorted(int(i) for i in (bb | mb | v) - set(grp.index))
    return out


def write_audit(c: dict, man: dict) -> None:
    f = man["files"][FILENAME]
    ov = c["overlap"]
    lines = [
        "# DATA AUDIT — Appelman et al. 2024 Source Data (Long COVID PEM study; blood and muscle metabolomics)",
        "",
        f"_Generated by `measure_it.ingestion.appelman_lc_pem` on {utc_now_iso()}; every count is computed from the "
        "retrieved file._",
        "",
        "| Field | Value |", "|---|---|",
        f"| source_id | {SOURCE_ID} |",
        f"| Source (dataset/API name, exact files/endpoints) | Source Data workbook `{FILENAME}` ({URL}); sheets "
        f"`{SHEET_BLOOD}` (venous plasma metabolomics), `{SHEET_MUSCLE}` (vastus lateralis metabolomics), "
        f"`{SHEET_DOMAIN_BLOOD}` / `{SHEET_DOMAIN_MUSCLE}` (authors' pathway domains), `{SHEET_DEMOG}` (sex, BMI, "
        f"comorbidity), `{SHEET_VO2}` (VO2max, peak power, GET) |",
        "| Publishing organization | Springer Nature (Nature Communications) on behalf of the authors (Amsterdam UMC / "
        "Vrije Universiteit Amsterdam; trial NCT05225688) |",
        f"| Retrieval date (UTC) | {f['retrieved_at']} |",
        f"| Source version / release | `{FILENAME}` (HTTP Last-Modified {f.get('last_modified', '')}); sha256 "
        f"{f['sha256']} |",
        "| Source update date / cadence | article published 2024-01-04; static |",
        "| License / access conditions | CC BY 4.0 (article and supplementary Source Data); anonymous download, no "
        "registration or DUA (verified 2026-09-24). Raw metabolomics also deposited (MetaboLights MTBLS9103; VU data "
        "platform 10.48338/VU01-KPABVO), not retrieved here. |",
        "| Unit of observation | person x timepoint (Baseline, 1 day after PEM induction, 1 week after, blood only) |",
        f"| Sample size (actual, as ingested) | {c['table1_people']} people in Table 1 "
        f"({json.dumps(c['table1_by_group_sex'])}); baseline blood metabolomics LC {ov['baseline_blood']['Long COVID']} "
        f"/ healthy {ov['baseline_blood']['Healthy']}; baseline muscle LC {ov['baseline_muscle']['Long COVID']} / "
        f"healthy {ov['baseline_muscle']['Healthy']} |",
        "| Geography (resolution, vintage) | none (single study site, Amsterdam; no participant geography) |",
        "| Person-level? | yes |", "| Geographic? | no |",
        f"| Omics? | yes: targeted polar metabolomics, {c['blood_metabolites']} plasma and {c['muscle_metabolites']} "
        "muscle metabolites (LC-MS; values normalised by the authors to plasma volume / dry tissue weight and "
        "internal standards) |",
        "| Wearable? | no metabolomics-wearable link used here (the paper's accelerometer steps are in "
        "`Supplementary Data Figure2C`, not ingested) |",
        "| True participant linkage across modalities? | yes, within this file: every sheet uses the same study `ID`; "
        "overlaps counted below. No key to Charlton 2026 (same trial, different numbering) or any other dataset. |",
        "",
        "## Files / endpoints retrieved", "",
        f"* `{FILENAME}` — {f['bytes']} bytes, sha256 `{f['sha256']}` (MANIFEST.json). The same file was earlier "
        "retrieved schema-only under `data/raw/device_candidates/appelman_lc_cpet_source/` by the device-dataset "
        "discovery sweep.",
        "* Paper full text read via Europe PMC (PMC10766651) for methods and the published claims.",
        "",
        "## Key variables", "",
        "* `ID` -> `participant_id = appelman_lc_pem_source:<ID>`; `Group` (Long COVID / Healthy) -> label; `Time` "
        "(Baseline / 1-day after PEM / 1-week after PEM).",
        "* Long COVID: symptoms >= 6 months after SARS-CoV-2 infection, PEM by DSQ-PEM, aged 18-65; healthy controls: "
        "age- and sex-matched people who fully recovered from mild COVID-19 (paper).",
        f"* `{SHEET_DEMOG}`: sex, BMI ({c['bmi_nonmissing']} non-missing), Charlson index, hospitalisation, "
        "vaccination, working hours, days since infection. **Age is not released** (column header: 'not shown for "
        f"privacy laws'; any value released: {c['age_released']}).",
        "* Metabolites: columns 4+ of the metabolomics sheets, one per metabolite, positive intensities; pathway "
        "domains from the domain sheets. There is no ME/CFS group in this file.",
        "",
        "## Missingness", "",
        "| tissue | metabolites | rows | Group x Time | missing cells | non-positive cells | people at baseline |",
        "|---|---:|---:|---|---:|---:|---:|",
    ]
    for t in ("blood", "muscle"):
        lines.append(f"| {t} | {c[f'{t}_metabolites']} | {c[f'{t}_rows']} | {json.dumps(c[f'{t}_group_time'])} | "
                     f"{c[f'{t}_missing_cells']} | {c[f'{t}_nonpositive_cells']} | {c[f'{t}_baseline_ids']} |")
    lines += ["", "Participant overlap (counted from shared `ID`s):", "",
              "| set | Long COVID | healthy |", "|---|---:|---:|"]
    for k, v in ov.items():
        lines.append(f"| {k} | {v['Long COVID']} | {v['Healthy']} |")
    lines += [
        "", f"IDs with data but not in Table 1: {c['ids_not_in_table1'] or 'none'}.", "",
        "## Linkage strategy", "",
        "Within-file joins on `ID` only (metabolomics x Table 1 x Figure1). Not joinable to Charlton 2026 rows (the "
        "same trial and probably largely the same people, but different ids), to NHANES, or to any geographic or "
        "facility layer. Condition-level molecular evidence elsewhere in the project is not person-linked to these "
        "people.",
        "", "## Limitations and caveats", "",
        "* 46 people; healthy controls only (no disease, deconditioning or ME/CFS comparator); patients able to "
        "undergo maximal CPET and biopsies (milder end); single site.",
        "* Age not released: models can adjust for sex (and BMI) only.",
        "* The authors excluded 4 muscle samples at QC and metabolites with > 5% missing values; the released values "
        "are post-QC and normalised (relative intensities, not absolute concentrations).",
        "* Same trial as Charlton 2026 (`charlton_lc_mecfs_cpet_source`): not independent evidence.",
        "", "## Processed outputs", "",
        "* `data/processed/phenotype_signatures__appelman_metabolomics` (written by "
        "`measure_it.labs.appelman_metabolomics`).",
        "* `results/tables/labs_dx_appelman_*.csv`; `results/LABS_VS_DIAGNOSIS_RESULTS.md` (Part 2).",
        "", "## Reproduce", "",
        "`uv run python -m measure_it.ingestion.appelman_lc_pem && uv run python -m measure_it.labs.appelman_metabolomics`",
        "",
    ]
    (raw_dir(SOURCE_ID) / "DATA_AUDIT.md").write_text("\n".join(lines))


def run() -> dict:
    p = fetch()
    man = load_manifest(SOURCE_ID)
    f = man["files"][FILENAME]
    assert hashlib.sha256(p.read_bytes()).hexdigest() == f["sha256"]
    c = _counts()
    write_audit(c, man)
    ov = c["overlap"]
    write_registry_entry({
        "source_id": SOURCE_ID,
        "name": "Appelman et al. 2024 Long COVID PEM study Source Data (plasma + muscle metabolomics, VO2max; "
                "Nat Commun 15:17)",
        "publisher": "Springer Nature / Nature Communications (authors: Amsterdam UMC, Vrije Universiteit Amsterdam)",
        "landing_url": f"https://doi.org/{DOI}",
        "access_urls": [URL],
        "license": "CC BY 4.0 (article and supplementary Source Data)",
        "access_conditions": "Open anonymous download; no registration or DUA (verified 2026-09-24).",
        "retrieved_at": f["retrieved_at"],
        "source_version": f"Source Data file {FILENAME} (HTTP Last-Modified {f.get('last_modified', '')}); "
                          f"sha256 {f['sha256']}",
        "update_date": "2024-01-04 (article publication; static)",
        "data_layer": "person",
        "unit_of_observation": "person x timepoint (baseline, 1 day and 1 week after PEM induction)",
        "sample_size": {
            "people_table1": c["table1_people"],
            "baseline_blood_long_covid": ov["baseline_blood"]["Long COVID"],
            "baseline_blood_healthy": ov["baseline_blood"]["Healthy"],
            "baseline_muscle_long_covid": ov["baseline_muscle"]["Long COVID"],
            "baseline_muscle_healthy": ov["baseline_muscle"]["Healthy"],
            "blood_metabolites": c["blood_metabolites"], "muscle_metabolites": c["muscle_metabolites"],
        },
        "geographic_resolution": "none",
        "person_level": True, "geographic": False, "omics": True, "wearable": False,
        "participant_linkage": "metabolomics (blood, muscle), Table 1 demographics and Figure1 VO2max share the "
                               "study ID within the file; no key to Charlton 2026 or other datasets",
        "true_participant_linkage_across_modalities": True,
        "status": "ingested",
        "processed_outputs": ["phenotype_signatures__appelman_metabolomics",
                              "results/tables/labs_dx_appelman_*.csv"],
        "audit": f"data/raw/{SOURCE_ID}/DATA_AUDIT.md",
        "ingestion_module": "measure_it.ingestion.appelman_lc_pem",
        "limitations": ["46 people; healthy controls only; no ME/CFS group in this file",
                        "age not released (sex and BMI only)",
                        "same trial as Charlton 2026 (NCT05225688): not independent evidence",
                        "relative, normalised intensities after the authors' QC"],
        "notes": "Appelman B, Charlton BT, Goulding RP, et al. Muscle abnormalities worsen after post-exertional "
                 "malaise in long COVID. Nat Commun 15, 17 (2024). doi:10.1038/s41467-023-44432-3 (PMC10766651). "
                 "Analysis: measure_it.labs.appelman_metabolomics under docs/ANALYSIS_PLAN_LABS_VS_DIAGNOSIS.md.",
    })
    return c


if __name__ == "__main__":
    print(json.dumps(run(), indent=2, default=str))
